version: '3.8'

services:
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    restart: always
    ports:
      - "${PORT:-8443}:8443"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - PORT=8443
    networks:
      - chat-network

volumes:
  portainer_data:

networks:
  chat-network:
    driver: bridge
