services:
  homepage:
    build: .
    container_name: chat-container
    ports:
      - "3000:80"
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
